apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
      version: 'v1'
  template:
    metadata:
      labels:
        app: api-gateway
        version: 'v1'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - api-gateway
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - name: api-gateway
          image: gcr.io/didyouwatch-329208/api-gateway
          env:
            - name: CONFIG_SERVER_URI
              value: "config-server-service:80"
          #            - name: SPRING_PROFILES_ACTIVE
          #              value: prod
          #            - name: JAVA_OPTS
          #              value: ' -Xmx256m -Xms256m -DSpring.profiles.active=${SPRING_PROFILES_ACTIVE}'
          resources:
            requests:
              memory: '512Mi'
              cpu: '250m'
            limits:
              memory: '1Gi'
              cpu: '500m'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 120

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
  labels:
    app: api-gateway-servcie
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
